### ISSUE TITLE
S3 Distribution Constructors

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#44]
There is a very strong argument to add S3 constructors for every implemented distribution for the less technical user.

e.g. `Binomial$new(size = 10, prob = 0.5) -> binom(size = 10, prob = 0.5)`

However to do so we need to be careful about the name of the constructors. I opt for the short name, i.e. Binomial = binom, Normal = norm, however this creates problems with things like Exponential = exp

**Comment by fkiraly** [comment]
Is there a problem using the class name (as is python convention, for example)?

**Comment by fkiraly** [comment]
Also, if the difference is only a few symbols, I'd discourage doing that.

It's a "best practice" design principle to not have too many redundant ways to do things. S3/R6 duality is already very close to the borderline for my taste

**Comment by RaphaelS1** [comment]
We could use classname but users may be more familiar with the shortname which is the same as R stats. I tend to agree with not having multiple ways to do something but with these S3 constructors and `R62S3`, a user can have an entirely S3 experience, without ever having to use R6 notation, whilst still using an interface built entirely with R6

**Comment by fkiraly** [comment]
Is there a technical restriction to just use the class name?

**Comment by RaphaelS1** [comment]
Yes unfortunately because (and correct me if I'm wrong) I don't think you can have an environment name (I.e. a class name) the same as a function name due to masking

**Comment by RaphaelS1** [comment]
Actually on second thoughts, given that we are using strict naming conventions and that classnames use UpperCamelCase and functions use lowerCamelCase, we could have constructors with the lowerCamelCase versions of the classnames. e.g. `Binomial$new -> binomial()` `FDist$new -> fdist()`

**Comment by RaphaelS1** [comment]
As discussed with Bernd today, all in agreement this isn't necessary
