### ISSUE TITLE
Should assertions be exported?

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#50]
Exporting assertions such as test/check/assert/isLeptokurtic means that anyone can use these functions externally, otherwise they only exist as internal helper functions. It currently takes my computer around half a minute to load the package, so there is definitely an argument to not export them. However a modelling package using distr6 may benefit from these assertions.

**Comment by fkiraly** [comment]
Is there a user friendly way to make this optional?

**Comment by RaphaelS1** [comment]
No, it has to be one or the other. Either they are exported when the package is created and the user can make use of them, or they are not and remain internal only. We could however export some and not others. For example we could export the functions `assertContinuous` and `assertDiscrete` but not export `assertVariateSupport` which is the generalisation of these.

**Comment by fkiraly** [comment]
Hm, then the main question becomes what the difference in loading time would be once the package is CRAN ready? It shouldn't take half a minute though, that seems oddly voluminous.

Are you referring to loading using devtools?

**Comment by RaphaelS1** [comment]
It turns out the loading problem was a strange background R activity that was taking up 99% of my CPU. No problems now, I think everything should be exported (as is currently the case and all is documented), this can probably be closed now
