### ISSUE TITLE
R62S3 compatibility issues, upgrade to R62S4 or R62Fun

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#51]
Due to complicated and precise documentation structures required in Roxygen, automatically generating and assigning S3 generics and methods is proving virtually impossible. However, there is no good reason to implement the dispatch system anyway as every single method is the same internally and therefore not class independent. On release of R62S3 v2, implement R62Fun in the zzz.r file.

**Comment by fkiraly** [comment]
Not sure whether I'm understanding the issue - is this mainly a roxygen problem, or a generics generation problem?

**Comment by RaphaelS1** [comment]
Both. The problem is that methods are not exported by roxygen whereas generics are. This is usually fine as both methods and generics live in the same namespace, methods are just not accessible to the user directly. However to document methods which don't exist (until the zzz.R file is called), docstrings have to be made on a NULL but this doesn't work for S3 methods so instead they are made on a place holder method i.e. 

```R
#' some docstrings...
#' @export
method.Class <- function() {}
```
but something goes wrong when assigning the correct methods to the namespace and they don't override this.

But I think the convenient release of R62S3 v2 which introduces R62S4 (for S4 method/generics) and R62Fun (name may be changed, introduces functions without being method/generic) will solve this.

**Comment by RaphaelS1** [comment]
Fixed. Upgraded to R62Fun using mask = FALSE and generic = TRUE. This means that any functions already existing like `pdf` are defined as `pdf.Distribution`. However I still think for consistency we should change `pdf` to `density` as per #43
