### ISSUE TITLE
Unlock binding CRAN cmd check notes

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#52]
Currently on build there is a note about unsafe calls to unlockBinding, this is currently required in construction of distributions and on change of support. There are clear ways of fixing this, e.g. by introducing more getters/setters and moving variables from private to public. If we can give a clear argument as to why we rely on unlockBinding however then it will pass CRAN submission. We can return to this before submission or see how it goes at the time.

**Comment by fkiraly** [comment]
Hm, would you mind pointing out where exactly this happens, under which conditions? E.g., why are there unsafe calls when we construct a distribution?

**Comment by RaphaelS1** [comment]
So the first thing to consider is that an R6 class is an environment, hence locking or unlocking a private variable is an unsafe call. This came up due to the following: for the vast majority of distributions properties are set in construction and then never changed, hence they can be stored as public variables. In R6 a public variable is an unlocked environment if in the class definition, it is NULL, it is a locked environment if in the class definition it is non-NULL. The Binomial distribution is an example of a distribution where the support changes if a parameter is updated, in this case "size" (which we have as settable). Hence to update the support, `property` is unlocked, updated, then locked. This could be changed by having the original definition as NULL and then fully defined in construction, then calls to `self` can be made without unlocking then locking the variable

**Comment by RaphaelS1** [comment]
Fixed, although this does open a new issue
