### ISSUE TITLE
Traits as variables or methods

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#56]
Due to the CRAN notes problem, properties are defined as follows:
* `.properties` is a private list holding the property details
*. `properties()` is a public getter

But traits are defined by a single `traits` list which is a locked environment (therefore un-editable). For consistency should we change traits so that it is defined like `properties` above?

**Comment by fkiraly** [comment]
Aren't there getters for particular traits, so it wouldn't strictly speaking necessary for usage?

Though I agree that for consistency it may make sense.

**Comment by RaphaelS1** [comment]
That was my thinking too

**Comment by RaphaelS1** [comment]
I think separating traits as variables and properties as methods naturally separates class and object properties. Also I think the slight inconsistency doesn't require a steep learning curve, so I'll keep the status quo
