### ISSUE TITLE
Error in exkurtosisType when undefined

### ISSUE THREAD

**Issue by britneyzeng** [RaphaelS1/distr6#59]
`exkurtosisType <- function(kurtosis){
  if(kurtosis < 0)
    return("platykurtic")
  else if(kurtosis == 0)
    return("mesokurtic")
  else
    return("leptokurtic")
}`

Problem: The kurtosis of some distributions is undefined in some cases eg.Student's t distribution. While the method exkurtosisType() require the argument kurtosis to be numeric and it didn't consider the undefined case.

**Comment by RaphaelS1** [comment]
- In the undefined case, should kurtosis (and skewness) return `NULL` or `NaN`. My suggestion is `NaN` as this is the standard convention (https://en.wikipedia.org/wiki/NaN).
- In line with `exKurtosisType` (analogously for skewness) returning character strings, my suggestion is adding
````R
if(is.nan(kurtosis)) return("undefined")
````

Opinions welcome, I'll implement the above late tomorrow if no-one has any objections to this suggestion.

**Comment by fkiraly** [comment]
@britneyzeng good find, this is also more generally true for other summaries like mean, variance, skew (Cauchy distribution doesn't have these).

I agree with @RaphaelS1 that it should be `NaN` when expected return type is `numeric`, and `undefined` when it is a string.
