### ISSUE TITLE
Efficient infinite sum calculations

### ISSUE THREAD

**Issue by w090613** [RaphaelS1/distr6#62]
Some of the equations listed in wiki involve infinite sum (e.g. entropy for poisson distribution and mgf for weibull distribution). I am trying to write functions to do the summation but also wondering if there is any other good ways to do it. 

Here is one example:
![poisson](https://user-images.githubusercontent.com/46967322/59444471-dd406680-8df5-11e9-9a10-94b96b35bfb7.PNG)

the code I used for the summation is 
    summation<-function (lambda){
      total<- vector(length=1000)
      for (i in 1:1000){
        total[i]<-exp(-lambda)*(lambda^i*log(factorial(i))/factorial(i))
      }
      sum(total)
    }

but I can't actually do an infinite sum. And the code will get slower if it includes as many terms.

**Comment by RaphaelS1** [comment]
Thanks for opening the issue. There's a few methods to do this, we definitely want to avoid `for` loops as they are inefficient. I can see two possible solutions: 1. We perfect my "working support" idea (can't remember the issue number now), or 2. We approximate using `integrate`

**Comment by RaphaelS1** [comment]
I'm leaning towards 1. as it avoids numerical integration, and should be fairly quick

**Comment by w090613** [comment]
Yeah, I am trying to understand 1 as integration is a bad estimation from my trials

**Comment by RaphaelS1** [comment]
(1.) utilises the idea that many results from `f(x)` for some distributions pdf, f, are sufficiently small that computationally they vanish. In R this 'small' number is around 1e-1000, but for many calculations we can set this tolerance to be much lower, say 1e-16. Then defining a distribution's support, S_X, so that S_X = {x: f(x) < 1e-16}, means that we never have to worry about infinite sums. (Let me know if this doesn't make sense to you!)

**Comment by w090613** [comment]
Thanks Raphael. It makes sense to me. Now will be the issue of perfecting working support idea

**Comment by fkiraly** [comment]
I believe there is no explicit analytical expression for the infinite sum - which is, of course, not a proof.
Though I remember looking for the state-of-art on this expression before when I was looking at the Poisson loss function:

@article{boersma1988solution,
  title={Solution to problem 87-6*: The entropy of a Poisson distribution},
  author={Boersma, J},
  journal={SIAM Review},
  volume={30},
  number={2},
  pages={314--317},
  year={1988}
}

@article{adell2010sharp,
  title={Sharp bounds on the entropy of the Poisson law and related quantities},
  author={Adell, Jos{\'e} A and Lekuona, Alberto and Yu, Yaming},
  journal={IEEE Transactions on Information Theory},
  volume={56},
  number={5},
  pages={2299--2306},
  year={2010},
  publisher={IEEE}
}

@PeterRuckdeschel , how does distr do it?

**Comment by RaphaelS1** [comment]
Hm according to the Boersma answer there's no closed form expression. Which means it is no better off than using `integrate` or "working support"

**Comment by fkiraly** [comment]
I don't think Boersma ever claims there is no closed form (reference?), as a negative would be a difficult statement to prove. The expressions may be computationally helpful though.

I wonder whether anyone has ever carefully reviewed the computational options there are, the entropy of a Poisson (and cross-entropies/KL-divergences) are quite fundamental quantities.

**Comment by RaphaelS1** [comment]
Sorry Boersma doesn't claim that there is *no* closed form, only that their conjecture still depends on an integral which they don't think "possible to evaluate in closed form"(p.317)

**Comment by PeterRuckdeschel** [comment]
I think you already found the right reference for the specific entropy sum. In more general situations involving expectations E(f(X)) where X ~ Pois(lambda) the usual recommended way is to use the duality relations between Poisson processes and exponential waiting times and hence to express this expectation in terms of gamma distributions.

I would also tend to think that a closed form in your case for model selection will only be of limited benefit, as long as the numeric accuracy provided by the approximation is fine enough to separate consistently candidate models.  

The usual numeric accuracy in R is abstracted from the actual OS/architecture by introducing the global constant .Machine$double.eps which should be used to capture machine-dependent accuracies.

**Comment by fkiraly** [comment]
PS @PeterRuckdeschel : regarding model selection: since differences and divergences are what tends to relevant in model selection, and those are usually easier to compute (since funny terms often cancel)

In any case, the Poisson loss, or poisson log-likelihoods, requre logarithms of factorials only for efficient computation and that's already done well by `lgamma`.

So I personally wouldn't be too unhappy with "lack of good solution for Poisson entropy":

**Comment by RaphaelS1** [comment]
Okay I think given that we have agreed that distributions should contain analytic results only, we shouldn't include entropy in the Poisson distribution. Then if someone really wants to find the result, they can use the `CoreStatistics` decorator. So @w090613 please don't include entropy in the distribution.
