### ISSUE TITLE
Defining Large  Rate in Possion

### ISSUE THREAD

**Issue by w090613** [RaphaelS1/distr6#63]
As listed in Wiki, for entropy of poisson, there are two equations used by the size of rate. I am wondering how large this lambda should be.
Some of the papers on google has mentioned rate=10 but the approximation is to another equation slightly different from wiki one. 
See https://pure.tue.nl/ws/portalfiles/portal/1959440/Metis199989.pdf for reference

**Comment by RaphaelS1** [comment]
As your own experiment. Could you test the equation for different thresholds for large lambda? So try both equations for rate = 1,10,20,30,50,100

**Comment by RaphaelS1** [comment]
From my own mini experiment just testing the absolute difference between the Poisson distribution and its Normal approximation at varying lambda, and from previous conventions, I am in favour of rate = 30. But I will defer to @fkiraly for a more mathematical answer.

**Comment by fkiraly** [comment]
Should this not be part of issue #62 ?

**Comment by fkiraly** [comment]
Also, what equation/threshold is this about?

**Comment by RaphaelS1** [comment]
> Should this not be part of issue #62 ?
I asked Xiaowen to separate them as this is a more general question about "when is the Poisson lambda parameter considered 'large'" which is an old question with no general consensus (although I was taught when lambda = 30).

> Also, what equation/threshold is this about?
Entropy of Poisson. For large lambda, there is a closed form analytic expression.

**Comment by fkiraly** [comment]
@RaphaelS1, the closed form is explicit only "up to lower order terms", i.e., an error term whose asymptotics you can derive. Without an explicit upper bound, though, you can't just set it to (numeric) zero.
It may require some calculations/derivations which we may want to avoid at this point?

**Comment by w090613** [comment]
Hi @RaphaelS1 , for my current code, the entropy using two different equations when rate =20 differ to an order of 10^-6 and when rate =30 differ to an order of 10^-7. The lowest difference is when rate is around 83 differing to an order of 10^-9.

**Comment by RaphaelS1** [comment]
Thanks for that @w090613. Let's use rate = 30 in the future when needed but for now as per #62 we won't include entropy.
