### ISSUE TITLE
Huberized distribution implemented incorrectly?

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#64]
This may be one that @PeterRuckdeschel can answer best as I am less familiar with huberization. Currently implemented as follows:

````R
  pdf <- function(x1, ...){
    pdf = x1
    pdf[x1 == self$inf()] <- rep(self$wrappedModels()[[1]]$cdf(self$inf()), sum(x1 == self$inf()))
    pdf[x1 == self$sup()] <- rep(self$wrappedModels()[[1]]$cdf(self$sup(), lower.tail = F) +
      self$wrappedModels()[[1]]$pdf(self$sup()), sum(x1 == self$sup()))
    pdf[x1 > self$inf() & x1 < self$sup()] <- self$wrappedModels()[[1]]$pdf(pdf[x1 > self$inf() & x1 < self$sup()])

    return(pdf)
  }
````

i.e. For huberized limits (a,b), Huberized distribution, H, with pdf f_X, and original distribution X, with pdf, f_X, cdf, F_X:

f_H(x) = 0, x < a or x > b
f_H(x) = F_X(x), x == a
f_H(x) = f_X(x), x > a and x < b
f_H(x) = (1 - F_X(x)) + f_X(x), x == b

Now for discrete distributions this behaves as expected, i.e. the sum of the pdf from a:b equals one however this does not hold for continuous distributions (pdf not integrating to on). Have I overlooked something?

**Comment by fkiraly** [comment]
The Huberization is not absolutely continuous, but mixed - so it doesn't make sense to define a pdf in the continuous case.

For cdf, this should be
F_H(x) = 0, x < a
F_H(x) = F_X(a), x = a
F_H(x) = 1, x >= b 
F_H(x) = F_X(x) otherwise

pdf is undefined in general.

**Comment by RaphaelS1** [comment]
Yes we've talked about this before and I completely forgot, and I found the same expression for cdf so that's good. Thanks!
