### ISSUE TITLE
wrong equation for "cumHazard"?

### ISSUE THREAD

**Issue by shliu99** [RaphaelS1/distr6#70]
Hi, I have noticed that on wiki page, the definition of the cumulative hazard function is 
**-log{S(t)}**, where S(t) denotes the survival function. But in the source code, it is computed as 
**-self$cdf(x1, log.p = TRUE)**. This means based on the current package, **self$cumHazard(x1)** does not the same solution as **-log(self$survival(x1))**.

I reckon the formula in our source code should be changed into **-self$survival(x1, log.p = TRUE)** and if that is the case, the corrected equation should be applied to all the distribution scripts.

**Comment by RaphaelS1** [comment]
Can you let me know which script you're looking in? Because in the dev branch I have `-self$survival(x1, log.p = TRUE) `

**Comment by shliu99** [comment]
Don't worry, think that's only because my scripts were pulled from the master branch so the version wasn't the most updated. That's all good now!

**Comment by RaphaelS1** [comment]
Great!
