### ISSUE TITLE
Infinitesimally Small Parameters and Propagation of Error

### ISSUE THREAD

**Issue by RaphaelS1** [RaphaelS1/distr6#90]
Some distribution parameters, for example the scale parameter in the Logistic distribution, take values greater than zero. There are three ways to implement this:

1. Edit parameter set to have an additional column identifying if parameters can take values on the lower and/or upper bounds
1. Set the lower value to `.Machine$double.eps = 2.220446e-16`
1. Add checks to every distribution with parameters such as this to assert the parameter value is greater than zero

I am in favour of option 2) as it is the most efficient and interpretable. However I am unsure if there is any risk of a propagation of error, e.g. when using automated methods to infer the value of the parameter is there any risk that by truncating the lower bound at 2.2e-16 we risk incorrectly estimating the parameter value and propagating this forward? I assume not as it's a very small difference, but as ever thoughts appreciated.

**Comment by fkiraly** [comment]
What about option 4., allowing open and closed sets for `distrDomain`?
"strictly positive" would be the domain (0, inf), in usual calculus notation.

**Comment by RaphaelS1** [comment]
This is specifically for parameters however given that we have a symbolic set interface I guess I could remove the "lower" and "upper" columns and replace these instead with "range" which takes as values a Set object? These allow for all four set combinations i.e. (),(],[),[]

**Comment by RaphaelS1** [comment]
Yes this actually makes more sense as it is in like with how distribution domains and supports are represented

**Comment by RaphaelS1** [comment]
*in line
